### ISSUE TITLE
Could not read Password error

### ISSUE THREAD

**Issue by MarkMpn** [ReneSorensen/VSTSTools#29]
I'm trying to use GitTag on a hosted DevOps Pipelines build agent using the following yaml:

```yaml
- task: GitTag@5
  displayName: Label Source
  inputs:
    workingdir: '$(Build.SourcesDirectory)'
    tag: 'v$(GitVersion.NuGetVersion)'
  env:
    SYSTEM_ACCESSTOKEN: '$(System.AccessToken)'
```

and I get the following log:

```
##[section]Starting: Label Source
==============================================================================
Task         : Git Tag
Description  : A simple task that tags a branch
Version      : 5.1.3
Author       : ATP P&I IT
Help         : tags the current branch with a specified tag. ### Prerequisites * Repository must be VSTS Git. * Allow scripts to access Oauth must be **Enabled** * Project Collection Build Service must have **Contribute** & **Create Tag** set to **Allow** or **Inherit Allow** for that particular repository
==============================================================================
Setting working directory to '/home/vsts/work/1/s'.
##[command]git config user.email "noreply@example.com"
##[command]git config user.name "VSTS"
##[command]git tag  -a "v0.2.2" -m "0.2.2+1"
Push tag to origin
##[command]git push origin v0.2.2
##[error]Command failed: git push origin v0.2.2 
fatal: could not read Password for 'https://xxxx@dev.azure.com': terminal prompts disabled

##[error]Git Repo Tagger Failed.
##[section]Finishing: Label Source
```

The "Allow scripts to access Oauth" option does not appear to be available with yaml pipelines, but I believe setting the `SYSTEM_ACCESSTOKEN` environment variable to `$(System.AccessToken)` should have the same effect. I've given the Project Collection Build Service Accounts group the Contribute and Create Tag permissions.
