### ISSUE TITLE
GitTag says it needs Windows Agent but works on linux

### ISSUE THREAD

**Issue by bryanbcook** [ReneSorensen/VSTSTools#33]
The description of the GitTag extension suggests that you need to give the script oAuth access and it needs to run on a Windows Host.  However, I've tried the GitTag@5 from my YAML build and it works fine on Linux machines, so what aspect of the extension requires a windows host?

My usage:

```
steps:
  - checkout: self
    persistCredentials: true

  - task: GitTag@5
    inputs:
      workingdir: '$(SYSTEM.DEFAULTWORKINGDIRECTORY)'
      tagUser: '$(Build.RequestedFor)'
      tagEmail: '$(Build.RequestedForEmail)'
      tag: '$(tag)'
      useLightweightTags: true
      forceTagCreation: true
```

The only messages that are suspect are the multiple ```(node:2581) Warning: Use Cipheriv for counter mode of aes-256-ctr``` messages that appear in the output. Not sure if that's the dependency?
